INSERT INTO players (player_name, team_id)
VALUES
    ('Guest 1', 1),
    ('Mark', 1),
    ('Jerry', 2),
    ('David', 3),
    ('Guest 1', 3),
    ('Tom', 4),
    ('Eric', 5),
    ('Guest 1', 5),
    ('Guest 2', 5),
    ('Guest 3', 5),
    ('Guest 4', 5),
    ('Kevin', 6),
    ('Jane', 7),
    ('Guest 1', 7),
    ('Guest 2', 7),
    ('Guest 3', 7),
    ('Guest 4', 7),
    ('Andrew', 8),
    ('Guest 1', 8),
    ('Guest 2', 8),
    ('Pat', 9),
    ('Jared', 9);